### ISSUE TITLE
ServiceDiscoveryManager LookupCache configured with single threaded ServiceEventExecutorService can report less than the required service added events.

### ISSUE THREAD

**Issue by pfirmstone** [pfirmstone/JGDMS#10]
Occurs when running the following test:
org.apache.river.test.impl.servicediscovery.event.LookupTaskServiceIdMapRace

**Comment by pfirmstone** [comment]
Work around:

Use at least two threads when configuring ServiceDiscoveryManager's ServiceEventExecutorService.

**Comment by pfirmstone** [comment]
Example test failure:

The LookupCache should notify that 6000 services are added.

In one instance the LookupCache only notified that 5999 services were added.

RegisterListenerTask, which is normally responsible for approximately 4500 service added notifications, while HandleServiceEventTask is usually responsible for the remaining 1500 service added notifications.

RegisterListenerTask, after registering to receive events calls lookup(ProxyReg) which populates the LookupCache and notifies of services added.  The lookup method eventually calls newOldService, which in turn calls filterMaybeDiscard.  

When HandleServiceEventTask is run, for each contiguous ServiceEvent received from the lookup service (no non contiguous events occur in a single threaded executor), it too calls newOldService, which in turn either calls filterMaybeDiscard or itemMatchMatchChange.

In the test failure above, newOldService was called 6007 times, while filterMaybeDiscard was called 5999 times and itemMatchMatchChange was called 6 times. filterMaybeDiscard + itemMatchMatchChange calls should = the total # of newOldService calls. In this case RegisterListenerTask was responsible for reporting 4507 service added events and HandleServiceEventTask responsible for 1492.

**Comment by pfirmstone** [comment]
[lookup cache - failure with concurrent logger - 1 SDM with wrong number of events.txt](https://github.com/pfirmstone/river-internet/files/559751/lookup.cache.-.failure.with.concurrent.logger.-.1.SDM.with.wrong.number.of.events.txt)

**Comment by pfirmstone** [comment]
[lookup cache - with concurrent logger - what passing looks like.txt](https://github.com/pfirmstone/river-internet/files/559761/lookup.cache.-.with.concurrent.logger.-.what.passing.looks.like.txt)

**Comment by pfirmstone** [comment]
ServiceDiscoveryManager and LookupCacheImpl have been modified to use a single threaded ExecutorService for logging, otherwise logging interferes with the concurrency of LookupCacheImpl and the test failures cannot be observed.

**Comment by pfirmstone** [comment]
This test failure can be observed in occasionally, in 2% of test runs with a single threaded ServiceEventExecutorService.

**Comment by pfirmstone** [comment]
This was caused by a ServiceEvent notification being received as soon as a new service was registered with the ServiceRegistrar, but prior to the service's join state receiving the ServiceRegistration, thus the ServiceIDAccessor didn't yet know the ServiceID.  Recommend changing the impl to use the ServiceEvent's reported ServiceID instead of using the ServiceIDAccessor api of the bootstrap proxy.

**Comment by pfirmstone** [comment]
NullPointerException that caused the test failures.    

```
 [java] Oct 31, 2016 9:15:03 AM net.jini.lookup.ServiceDiscoveryManager lambda$log$0
 [java] FINE: Runtime exception thrown in newOldService call
 [java] java.lang.NullPointerException
 [java]     at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
 [java]     at net.jini.lookup.LookupCacheImpl.newOldService(LookupCacheImpl.java:1313)
 [java]     at net.jini.lookup.LookupCacheImpl.notifyServiceMap(LookupCacheImpl.java:1188)
 [java]     at net.jini.lookup.LookupCacheImpl.access$1700(LookupCacheImpl.java:93)
 [java]     at net.jini.lookup.LookupCacheImpl$HandleServiceEventTask.run(LookupCacheImpl.java:1084)
 [java]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 [java]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 [java]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 [java]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 [java]     at java.lang.Thread.run(Thread.java:745)
 [java] 
```
