### ISSUE TITLE
DynamicPolicyProvider doesn't call decorated policy implies method for system policy

### ISSUE THREAD

**Issue by pfirmstone** [pfirmstone/JGDMS#178]
**Describe the bug**
org.apache.river.api.security.ConcurrentPermissions fails to resolve UnresolvedPermission

**To Reproduce**
Tested using jdk-authorization with trunk branch as at 23/11/2024 4:18PM AEST
qa/src/org/apache/river/qa/resources/qaDefaults.properties
With:
-Djava.security.manager=default, for all jvm instances, after auditing test policy files with -Djava.security.manager=polpAudit

with the following set in build.properties in the JGDMS project directory:
run.tests=org/apache/river/test/impl/outrigger/transaction/PreparedTransactionTestAbort.td

Executing in the qa directory after building tests with Java 8:
ant run-tests

**Expected behavior**

DeSerializationPermission should be resolved.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Pro, 22H2 30/10/2022 19045.5011  Windows Feature Pack 1000.19060.100.0
 - JGDMS trunk branch
**Additional context**

Debug output:
     [java] java.lang.Exception: Stack trace
     [java]     at java.base/java.lang.Thread.dumpStack(Thread.java:2155)
     [java]     at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:483)
     [java]     at java.base/au.zeus.jdk.authorization.sm.CombinerSecurityManager.checkPermission(CombinerSecurityManager.java:341)
     [java]     at org.apache.river.api.io.ObjectStreamClassContainer.deSerializationPermitted(ObjectStreamClassContainer.java:145)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readNewObject(AtomicMarshalInputStream.java:2533)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readNonPrimitiveContent(AtomicMarshalInputStream.java:967)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readObject(AtomicMarshalInputStream.java:3026)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readFieldValues(AtomicMarshalInputStream.java:1268)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readFields(AtomicMarshalInputStream.java:1200)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.instantiateAtomicSerialOrDiscard(AtomicMarshalInputStream.java:2792)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readNewObject(AtomicMarshalInputStream.java:2536)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readNonPrimitiveContent(AtomicMarshalInputStream.java:967)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readObject(AtomicMarshalInputStream.java:3026)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readObjectOverride(AtomicMarshalInputStream.java:2926)
     [java]     at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:515)
     [java]     at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:482)
     [java]     at org.apache.river.qa.harness.MasterTest.main(MasterTest.java:119)
     [java] access: domain that failed DomainCombinerSecurityManager full stack:
     [java] ProtectionDomain  (file:/C:/Users/peter/Documents/GitHub/JGDMS/JGDMS/dist/target/JGDMS-3.1.1-SNAPSHOT/lib/jgdms-platform-3.1.1-SNAPSHOT.jar <no signer certificates>)
     [java]  jdk.internal.loader.ClassLoaders$AppClassLoader@97e1986
     [java]  <no principals>
     [java]  org.apache.river.api.security.ConcurrentPermissions@6b415f5f (
     [java]  (unresolved org.apache.river.api.io.DeSerializationPermission ATOMIC )
     [java]  (unresolved org.apache.river.jeri.internal.EndpointInternalsPermission set )
     [java]  ("java.io.SerializablePermission" "enableSubclassImplementation")
     [java]  ("java.io.SerializablePermission" "enableSubstitution")
     [java]  ("java.util.logging.LoggingPermission" "control")
     [java]  ("java.lang.RuntimePermission" "getProtectionDomain")
     [java]  ("java.lang.RuntimePermission" "createSecurityManager")
     [java]  ("java.lang.RuntimePermission" "getStackWalkerWithClassReference")
     [java]  ("java.lang.RuntimePermission" "createClassLoader")
     [java]  ("java.lang.RuntimePermission" "getClassLoader")
     [java]  ("java.lang.RuntimePermission" "accessDeclaredMembers")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.connectionTimeout" "read")
     [java]  ("java.util.PropertyPermission" "java.specification.version" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.tcp.useNIO" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.kerberos.KerberosEndpoint.maxGssContextRetries" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.vendor" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.dgc.minimumDuration" "read")
     [java]  ("java.util.PropertyPermission" "net.jini.discovery.timeout" "read")
     [java]  ("java.util.PropertyPermission" "java.rmi.server.codebase" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.ssl.jsseProvider" "read")
     [java]  ("java.util.PropertyPermission" "java.vendor.url" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.specification.version" "read")
     [java]  ("java.util.PropertyPermission" "os.name" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.activation.enableActivateGrant" "read")
     [java]  ("java.util.PropertyPermission" "net.jini.activation.port" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.handshakeTimeout" "read")
     [java]  ("java.util.PropertyPermission" "java.specification.vendor" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.kerberos.KerberosEndpoint.maxCacheSize" "read")
     [java]  ("java.util.PropertyPermission" "file.separator" "read")
     [java]  ("java.util.PropertyPermission" "line.separator" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.specification.vendor" "read")
     [java]  ("java.util.PropertyPermission" "java.specification.name" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.dgc.cleanInterval" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.connection.mux.server.initialInboundRation" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.ssl.cipherSuites" "read")
     [java]  ("java.util.PropertyPermission" "net.jini.loader.codebaseAnnotation" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.outrigger.maxServerQueryTimeout" "read")
     [java]  ("java.util.PropertyPermission" "path.separator" "read")
     [java]  ("java.util.PropertyPermission" "os.version" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.ssl.secureRandomAlgorithm" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.dgc.leaseValue" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.ssl.sslProtocol" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.ssl.jceProvider" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.name" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.server.suppressStackTraces" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.kerberos.KerberosEndpoint.minGssContextLifetime" "read")
     [java]  ("java.util.PropertyPermission" "java.version" "read")
     [java]  ("java.util.PropertyPermission" "os.arch" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.specification.name" "read")
     [java]  ("java.util.PropertyPermission" "net.jini.loader.ClassLoading.provider" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.connection.mux.client.initialInboundRation" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.dgc.checkInterval" "read")
     [java]  ("java.util.PropertyPermission" "java.vendor" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.version" "read")
     [java]  ("java.util.PropertyPermission" "java.specification.maintenance.version" "read")
     [java]  ("java.util.PropertyPermission" "java.rmi.server.hostname" "read")
     [java]  ("java.util.PropertyPermission" "net.jini.security.allowInsecureConnections" "read")
     [java]  ("java.util.PropertyPermission" "java.class.version" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.jeri.ssl.certificateType" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\harness\configs\jsse\test.config" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\JGDMS\dist\target\JGDMS-3.1.1-SNAPSHOT\lib\jgdms-pref-class-loader-3.1.1-SNAPSHOT.jar" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\src\org\apache\river\test\impl\outrigger\configs\jsse\default.config" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\lib\jinitests.jar" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\JGDMS\dist\target\JGDMS-3.1.1-SNAPSHOT\lib\jgdms-discovery-providers-3.1.1-SNAPSHOT.jar" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\JGDMS\dist\target\JGDMS-3.1.1-SNAPSHOT\lib\jgdms-url-integrity-3.1.1-SNAPSHOT.jar" "read")
     [java]  ("java.net.SocketPermission" "DESKTOP-7H6KHM0" "connect,accept,resolve")
     [java]  ("java.net.SocketPermission" "localhost:0" "listen,resolve")
     [java]  ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
     [java]  ("java.security.SecurityPermission" "createPolicy.JiniPolicy")
     [java]  ("java.security.SecurityPermission" "getDomainCombiner")
     [java]  ("java.security.SecurityPermission" "createAccessControlContext")
     [java]  ("java.security.SecurityPermission" "getPolicy")
     [java]  ("javax.security.auth.AuthPermission" "getSubject")
     [java]  ("javax.security.auth.AuthPermission" "createLoginContext.org.apache.river.Test")
     [java]  (unresolved org.apache.river.jeri.internal.EndpointInternalsPermission set )
     [java]  (unresolved org.apache.river.api.io.DeSerializationPermission ATOMIC )
     [java]  ("au.zeus.jdk.authorization.guards.LoadClassPermission" "ALLOW")
     [java] )

**Comment by pfirmstone** [comment]
This doesn't appear to be an issue with ConcurrentPermissions as the same thing is happening with Permissions.

Suspect this is something to do with changes to reflection permissions in jdk-authorization trunk under test.

     [java] access: access denied ("org.apache.river.api.io.DeSerializationPermission" "ATOMIC")
     [java] java.lang.Exception: Stack trace
     [java]     at java.base/java.lang.Thread.dumpStack(Thread.java:2155)
     [java]     at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:483)
     [java]     at java.base/au.zeus.jdk.authorization.sm.CombinerSecurityManager.checkPermission(CombinerSecurityManager.java:341)
     [java]     at org.apache.river.api.io.ObjectStreamClassContainer.deSerializationPermitted(ObjectStreamClassContainer.java:145)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readNewObject(AtomicMarshalInputStream.java:2533)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readNonPrimitiveContent(AtomicMarshalInputStream.java:967)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readObject(AtomicMarshalInputStream.java:3026)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readObjectOverride(AtomicMarshalInputStream.java:2926)
     [java]     at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:515)
     [java]     at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:482)
     [java]     at org.apache.river.qa.harness.MasterTest.main(MasterTest.java:119)
     [java] access: domain that failed DomainCombinerSecurityManager full stack:
     [java] ProtectionDomain  (file:/C:/Users/peter/Documents/GitHub/JGDMS/qa/lib/jiniharness.jar <no signer certificates>)
     [java]  jdk.internal.loader.ClassLoaders$AppClassLoader@97e1986
     [java]  <no principals>
     [java]  java.security.Permissions@798deee8 (
     [java]  ("java.io.FilePermission" "org\apache\river\test\impl\outrigger\configs\jsse\default.config" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\soul\soul.202411201847003864" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\soul\soul.202411211359057164" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\soul\soul.202411202044017903" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\harness\configs\jsse\test.config" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\src\org\apache\river\test\impl\outrigger\configs\jsse\default.config" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\src\org\apache\river\test\impl\outrigger\transaction\org\apache\river\test\impl\outrigger\configs\jsse\default.config" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\soul\soul.202411231520007839" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\soul\soul.202411201910039187" "read")
     [java]  ("java.io.FilePermission" "C:\Users\peter\Documents\GitHub\JGDMS\qa\soul\soul.202411231459001032" "read")
     [java]  ("java.net.SocketPermission" "localhost:0" "listen,resolve")
     [java]  ("java.io.SerializablePermission" "enableSubclassImplementation")
     [java]  ("java.util.logging.LoggingPermission" "control")
     [java]  ("java.lang.RuntimePermission" "getenv.SOUL")
     [java]  ("java.lang.RuntimePermission" "getStackWalkerWithClassReference")
     [java]  ("java.lang.RuntimePermission" "setIO")
     [java]  ("javax.security.auth.AuthPermission" "createLoginContext.org.apache.river.Test")
     [java]  ("javax.security.auth.AuthPermission" "doAsPrivileged")
     [java]  ("java.util.PropertyPermission" "java.specification.version" "read")
     [java]  ("java.util.PropertyPermission" "path.separator" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.vendor" "read")
     [java]  ("java.util.PropertyPermission" "os.version" "read")
     [java]  ("java.util.PropertyPermission" "java.vendor.url" "read")
     [java]  ("java.util.PropertyPermission" "os.name" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.specification.version" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.name" "read")
     [java]  ("java.util.PropertyPermission" "net.jini.discovery.announce" "read")
     [java]  ("java.util.PropertyPermission" "testConfiguration" "read")
     [java]  ("java.util.PropertyPermission" "java.version" "read")
     [java]  ("java.util.PropertyPermission" "user.dir" "read")
     [java]  ("java.util.PropertyPermission" "os.arch" "read")
     [java]  ("java.util.PropertyPermission" "loader.requireDlPerm" "read")
     [java]  ("java.util.PropertyPermission" "java.specification.vendor" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.specification.name" "read")
     [java]  ("java.util.PropertyPermission" "file.separator" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.qa.harness.defaultTestConfig" "read")
     [java]  ("java.util.PropertyPermission" "line.separator" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.specification.vendor" "read")
     [java]  ("java.util.PropertyPermission" "java.vendor" "read")
     [java]  ("java.util.PropertyPermission" "java.specification.name" "read")
     [java]  ("java.util.PropertyPermission" "testFailureAnalyzers" "read")
     [java]  ("java.util.PropertyPermission" "java.vm.version" "read")
     [java]  ("java.util.PropertyPermission" "org.apache.river.qa.harness.testhosts" "read")
     [java]  ("java.util.PropertyPermission" "java.specification.maintenance.version" "read")
     [java]  ("java.util.PropertyPermission" "net.jini.security.allowInsecureConnections" "read")
     [java]  ("java.util.PropertyPermission" "java.class.version" "read")
     [java]  (unresolved org.apache.river.api.io.DeSerializationPermission ATOMIC )
     [java]  ("au.zeus.jdk.authorization.guards.LoadClassPermission" "ALLOW")
     [java]  ("java.security.SecurityPermission" "createPolicy.JiniPolicy")
     [java]  ("java.security.SecurityPermission" "getPolicy")
     [java]  ("java.security.SecurityPermission" "setPolicy")
     [java] )
     [java]
     [java]
     [java] java.security.AccessControlException: access denied ("org.apache.river.api.io.DeSerializationPermission" "ATOMIC")
     [java]     at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:493)
     [java]     at java.base/au.zeus.jdk.authorization.sm.CombinerSecurityManager.checkPermission(CombinerSecurityManager.java:341)
     [java]     at org.apache.river.api.io.ObjectStreamClassContainer.deSerializationPermitted(ObjectStreamClassContainer.java:145)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readNewObject(AtomicMarshalInputStream.java:2533)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readNonPrimitiveContent(AtomicMarshalInputStream.java:967)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readObject(AtomicMarshalInputStream.java:3026)
     [java]     at org.apache.river.api.io.AtomicMarshalInputStream.readObjectOverride(AtomicMarshalInputStream.java:2926)
     [java]     at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:515)
     [java]     at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:482)
     [java]     at org.apache.river.qa.harness.MasterTest.main(MasterTest.java:119)

**Comment by pfirmstone** [comment]
Since the policy creates PermissionCollection's on demand and then discards, during debug output, UnresolvedPermissions will show as unresolved, this doesn't mean the permission wasn't resolved during the policy implies check, also the static and policy permissions are merged during debug output.

**Comment by pfirmstone** [comment]
This only occurs when using the Java platform policy implementation, if using ConcurrentPolicyFile this doesn't occur.  The fix is to call the platform policy implies method.
