### ISSUE TITLE
Module :: JGDMS Jini Platform - net.jini.loader.LoadClass waiting forever to load a class.

### ISSUE THREAD

**Issue by pfirmstone** [pfirmstone/JGDMS#30]
One test was unable to shut down due to a lack of a timeout while attempting to load a class, the test waited for 5 hours until I killed the process that was waiting to load the class.  After the process was killed the test passed.

**Comment by pfirmstone** [comment]
[java] Running org/apache/river/test/impl/servicediscovery/event/DiscardDownReDiscover.td
     [java] Time is Sat Aug 05 21:16:39 EST 2017
     [java] Starting test in separate process with command:
     [java] 'C:\Program Files\Java\jdk1.8.0\jre\bin\java' -Djava.security.manager=org.apache.river.api.security.CombinerSecurityManager -Djava.security.policy=f
ile:/C:/Users/peter/Documents/NetBeansProjects/river-internet/qa/harness/policy/defaulttest.policy -Djava.rmi.server.codebase=http://medusa:9082/qa1-servicedisc
overy-dl.jar -cp C:\Users\peter\Documents\NetBeansProjects\river-internet\qa\lib\jiniharness.jar;C:\Users\peter\Documents\NetBeansProjects\river-internet\qa\lib
\jinitests.jar;C:\Users\peter\Documents\NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib\jgdms-discovery-providers-3.0-SNAPSHOT.jar;C:\U
sers\peter\Documents\NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib\jgdms-pref-class-loader-3.0-SNAPSHOT.jar;C:\Users\peter\Documents\
NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib\classserver-3.0-SNAPSHOT.jar;C:\Users\peter\Documents\NetBeansProjects\river-internet/J
GDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib\jgdms-jeri-3.0-SNAPSHOT.jar;C:\Users\peter\Documents\NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-3.0-SNAPSHO
T\lib\jgdms-platform-3.0-SNAPSHOT.jar;C:\Users\peter\Documents\NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib\jgdms-collections-3.0-SN
APSHOT.jar;C:\Users\peter\Documents\NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib\jgdms-lib-3.0-SNAPSHOT.jar;C:\Users\peter\Documents
\NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib\service-starter-3.0-SNAPSHOT.jar;C:\Users\peter\Documents\NetBeansProjects\river-inter
net/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib-dl\jgdms-lib-dl-3.0-SNAPSHOT.jar;C:\Users\peter\Documents\NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-3
.0-SNAPSHOT\lib\high-scale-lib-1.0.6.jar;C:\Users\peter\Documents\NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib\jgdms-activation-3.0-
SNAPSHOT.jar;C:\Users\peter\Documents\NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib-dl\phoenix-dl-3.0-SNAPSHOT.jar;C:\Users\peter\Doc
uments\NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib\phoenix-init-3.0-SNAPSHOT.jar;C:\Users\peter\Documents\NetBeansProjects\river-in
ternet/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT\lib\jgdms-destroy-3.0-SNAPSHOT.jar;C:\Users\peter\Documents\NetBeansProjects\river-internet/JGDMS/dist/target/JGDMS-
3.0-SNAPSHOT\lib\jgdms-url-integrity-3.0-SNAPSHOT.jar -ea -esa -Djava.net.preferIPv6Addresses=true -Dorg.cliffc.high_scale_lib.jar=high-scale-lib-1.0.6.jar -Dor
g.apache.river.discovery.jar=jgdms-discovery-providers-3.0-SNAPSHOT.jar -Dorg.apache.river.collections.jar=jgdms-collections-3.0-SNAPSHOT.jar -Dorg.apache.river
.start.jar=service-starter-3.0-SNAPSHOT.jar -Dorg.apache.river.start.destroy.jar=jgdms-destroy-3.0-SNAPSHOT.jar -Dorg.apache.river.start.group.jar=group-service
-3.0-SNAPSHOT.jar -Dorg.apache.river.start.group.dl.jar=group-dl-3.0-SNAPSHOT.jar -Dorg.apache.river.fiddler.jar=fiddler-service-3.0-SNAPSHOT.jar -Dorg.apache.r
iver.fiddler.dl.jar=fiddler-dl-3.0-SNAPSHOT.jar -Dorg.apache.river.mahalo.jar=mahalo-service-3.0-SNAPSHOT.jar -Dorg.apache.river.mahalo.dl.jar=mahalo-dl-3.0-SNA
PSHOT.jar -Dorg.apache.river.mercury.jar=mercury-service-3.0-SNAPSHOT.jar -Dorg.apache.river.mercury.dl.jar=mercury-dl-3.0-SNAPSHOT.jar -Dorg.apache.river.norm.
jar=norm-service-3.0-SNAPSHOT.jar -Dorg.apache.river.norm.dl.jar=norm-dl-3.0-SNAPSHOT.jar -Dorg.apache.river.outrigger.jar=outrigger-service-3.0-SNAPSHOT.jar -D
org.apache.river.outrigger.dl.jar=outrigger-dl-3.0-SNAPSHOT.jar -Dorg.apache.river.outrigger.snaplogstore.jar=outrigger-snaplogstore-3.0-SNAPSHOT.jar -Dorg.apac
he.river.reggie.jar=reggie-service-3.0-SNAPSHOT.jar -Dorg.apache.river.reggie.dl.jar=reggie-dl-3.0-SNAPSHOT.jar -Dorg.apache.river.lib.jar=jgdms-lib-3.0-SNAPSHO
T.jar -Dnet.jini.activation.jar=jgdms-activation-3.0-SNAPSHOT.jar -Dnet.jini.lib.dl.jar=jgdms-lib-dl-3.0-SNAPSHOT.jar -Dnet.jini.platform.jar=jgdms-platform-3.0
-SNAPSHOT.jar -Dnet.jini.jeri.jar=jgdms-jeri-3.0-SNAPSHOT.jar -Dnet.jini.iiop.jar=jgdms-iiop-3.0-SNAPSHOT.jar -Dnet.jini.jrmp.jar=jgdms-jrmp-3.0-SNAPSHOT.jar -D
net.jini.pref.jar=jgdms-pref-class-loader-3.0-SNAPSHOT.jar -Dnet.jini.url.jar=jgdms-url-integrity-3.0-SNAPSHOT.jar -Dorg.apache.river.tool.classserver.jar=class
server-3.0-SNAPSHOT.jar -Dorg.apache.river.phoenix.jar=phoenix-3.0-SNAPSHOT.jar -Dorg.apache.river.phoenix.common.jar=phoenix-common-3.0-SNAPSHOT.jar -Dorg.apac
he.river.phoenix.dl.jar=phoenix-dl-3.0-SNAPSHOT.jar -Dorg.apache.river.phoenix.group.jar=phoenix-group-3.0-SNAPSHOT.jar -Dorg.apache.river.phoenix.init.jar=phoe
nix-init-3.0-SNAPSHOT.jar -Dorg.apache.river.jsk.port=9080 -Dorg.apache.river.qa.port=9081 -Dorg.apache.river.jsk.home=C:\Users\peter\Documents\NetBeansProjects
\river-internet/JGDMS/dist/target/JGDMS-3.0-SNAPSHOT -Dorg.apache.river.qa.home=C:\Users\peter\Documents\NetBeansProjects\river-internet\qa -Dorg.apache.river.q
a.harness.harnessJar=C:\Users\peter\Documents\NetBeansProjects\river-internet\qa\lib\jiniharness.jar -Dorg.apache.river.qa.harness.testJar=C:\Users\peter\Docume
nts\NetBeansProjects\river-internet\qa\lib\jinitests.jar -Dorg.apache.river.qa.harness.runjiniserver=true -Dorg.apache.river.qa.harness.runkitserver=true -Djava
.security.properties=file:/C:/Users/peter/Documents/NetBeansProjects/river-internet/qa/harness/trust/dynamic-policy.properties -Dorg.apache.river.qa.harness.tes
thosts= -Djava.util.logging.config.file=C:\Users\peter\Documents\NetBeansProjects\river-internet\qa\src\org\apache\river\test\resources\qa1.logging -Dnet.jini.c
ore.lookup.ServiceRegistrar.portAbitraryIfInUse=true -Dorg.apache.river.test.home=C:\Users\peter\Documents\NetBeansProjects\river-internet\qa -Dorg.apache.river
.test.port=9082 -Dorg.apache.river.qa.harness.policies=file:/C:/Users/peter/Documents/NetBeansProjects/river-internet/qa/src/org/apache/river/test/resources/jin
itest.policy -Dorg.apache.river.sdm.discardWait=60000 -DtestCategories=servicediscovery,servicediscovery_impl,servicediscoveryevent,implservicediscovery,implser
vicediscoveryevent,discardproblem -Dnet.jini.lookup.nSecsServiceDiscovery=20 -Dinclude1=org/apache/river/test/impl/servicediscovery/event/Discard.properties -Dn
et.jini.lookup.nLookupServices=2 -Dinclude0=../servicediscovery.properties -Dnet.jini.lookup.nAddAttributes=0 -Dnet.jini.lookup.nAttributes=0 -DtestClass=Discar
dDownReDiscover -Dnet.jini.lookup.nSecsLookupDiscovery=10 -Dnet.jini.lookup.nServices=12 '-DtestOverrideProviders=${testOverrideProviders} org.apache.river.test
.spec.servicediscovery.DiscardWaitOverrideProvider' -Dnet.jini.discovery.nIntervalsToWait=2 -Dnet.jini.lookup.nAddLookupServices=0 -Dnet.jini.discovery.maxSecsE
ventWait=180 -DtestConfiguration=<url:org/apache/river/test/spec/servicediscovery/configs/<config>/default.config> -Dnet.jini.core.lookup.ServiceRegistrar.membe
rgroups.0=SDMGroup0 -Dnet.jini.lookup.nAddServices=0 -DtestCodebase=http://${HOST}:${org.apache.river.test.port}/qa1-servicediscovery-dl.jar -Dorg.apache.river.
sdm.debug=true org.apache.river.qa.harness.MasterTest org/apache/river/test/impl/servicediscovery/event/DiscardDownReDiscover.td
     [java]
     [java] TIME: 9:16:40 PM
     [java]
     [java] MasterTest.doTest INFO:
     [java] ============================== CALLING CONSTRUCT() ==============================
     [java]
     [java]
     [java] TIME: 9:17:17 PM
     [java]
     [java] MasterTest.doTest INFO:
     [java] =============================== CALLING RUN() ===============================
     [java]
     [java]
     [java] TIME: 9:26:12 PM
     [java]
     [java] MasterTest.doTest INFO:
     [java] ============================ CALLING TEARDOWN() =============================
     [java]

After Killing 4952.txt

     [java] java.rmi.UnmarshalException: exception unmarshalling response; nested exception is:
     [java]     java.io.IOException: I/O error reading from mux connection: java.net.SocketException: Connection reset
     [java]     at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:908)
     [java]     at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:708)
     [java]     at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:577)
     [java]     at com.sun.proxy.$Proxy3.cancelServiceLease(Unknown Source)
     [java]     at org.apache.river.reggie.proxy.ServiceLease.cancel(ServiceLease.java:101)
     [java]     at net.jini.lease.LeaseRenewalManager.cancel(LeaseRenewalManager.java:1210)
     [java]     at org.apache.river.test.spec.servicediscovery.AbstractBaseTest.unregisterServices(AbstractBaseTest.java:885)
     [java]     at org.apache.river.test.spec.servicediscovery.AbstractBaseTest.tearDown(AbstractBaseTest.java:580)
     [java]     at org.apache.river.qa.harness.MasterTest.doTest(MasterTest.java:282)
     [java]     at org.apache.river.qa.harness.MasterTest.main(MasterTest.java:144)
     [java] Caused by: java.io.IOException: I/O error reading from mux connection: java.net.SocketException: Connection reset
     [java]     at org.apache.river.jeri.internal.mux.Session.setDown(Session.java:299)
     [java]     at org.apache.river.jeri.internal.mux.Mux$SessionShutdownTask.run(Mux.java:109)
     [java]     at org.apache.river.jeri.internal.mux.Mux$1.run(Mux.java:339)
     [java]     at org.apache.river.thread.ThreadPool$Task.run(ThreadPool.java:172)
     [java]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [java]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [java]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [java]     at java.lang.Thread.run(Thread.java:744)
     [java] Caused by: java.net.SocketException: Connection reset
     [java]     at java.net.SocketInputStream.read(SocketInputStream.java:189)
     [java]     at java.net.SocketInputStream.read(SocketInputStream.java:121)
     [java]     at org.apache.river.jeri.internal.mux.StreamConnectionIO$1.read(StreamConnectionIO.java:371)
     [java]     at org.apache.river.jeri.internal.mux.StreamConnectionIO$Reader.run(StreamConnectionIO.java:276)
     [java]     ... 6 more
     [java]
     [java] TIME: 2:21:34 PM
     [java]
     [java] NonActivatableServiceStarterAdmin.stop INFO: Service Object is gone, presumed killed by test
     [java] NonActivatableServiceStarterAdmin.stop INFO: Service Object is gone, presumed killed by test
     [java]
     [java] TIME: 2:21:40 PM
     [java]
     [java] Test process was destroyed and returned code 0
     [java] org/apache/river/test/impl/servicediscovery/event/DiscardDownReDiscover.td
     [java] Test Passed: OK

Processes:
4952.txt
2796.txt
4352.txt
4040.txt

It looks like there was a problem waiting for a class to be loaded in process 4952.
[4040.txt](https://github.com/pfirmstone/JGDMS/files/1202870/4040.txt)
[4352.txt](https://github.com/pfirmstone/JGDMS/files/1202871/4352.txt)
[2796.txt](https://github.com/pfirmstone/JGDMS/files/1202872/2796.txt)
[4952.txt](https://github.com/pfirmstone/JGDMS/files/1202875/4952.txt)

The offending stack trace:

"(JSK) mux request dispatch" #116 prio=5 os_prio=0 tid=0x3f265c00 nid=0x1340 waiting on condition [0x3ff8e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x11861460> (a java.util.concurrent.FutureTask)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at net.jini.loader.LoadClass.forName(LoadClass.java:114)
	at net.jini.loader.pref.PreferredClassProvider.loadClass(PreferredClassProvider.java:688)
	at net.jini.loader.ClassLoading.loadClass(ClassLoading.java:354)
	at net.jini.io.MarshalInputStream.resolveClass(MarshalInputStream.java:329)
	at org.apache.river.api.io.AtomicMarshalInputStream.readNewClassDesc(AtomicMarshalInputStream.java:2026)
	at org.apache.river.api.io.AtomicMarshalInputStream.readClassDesc(AtomicMarshalInputStream.java:821)
	at org.apache.river.api.io.AtomicMarshalInputStream.readNewObject(AtomicMarshalInputStream.java:2251)
	at org.apache.river.api.io.AtomicMarshalInputStream.readNonPrimitiveContent(AtomicMarshalInputStream.java:936)
	at org.apache.river.api.io.AtomicMarshalInputStream.readObject(AtomicMarshalInputStream.java:2746)
	at org.apache.river.api.io.AtomicMarshalInputStream.readObjectOverride(AtomicMarshalInputStream.java:2647)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:365)
	at org.apache.river.jeri.internal.runtime.Util.unmarshalValue(Util.java:225)
	at net.jini.jeri.BasicInvocationDispatcher.unmarshalArguments(BasicInvocationDispatcher.java:1209)
	at net.jini.jeri.BasicInvocationDispatcher.dispatch(BasicInvocationDispatcher.java:690)
	at org.apache.river.jeri.internal.runtime.Target$2.run(Target.java:493)
	at net.jini.export.ServerContext.doWithServerContext(ServerContext.java:113)
	at org.apache.river.jeri.internal.runtime.Target.dispatch(Target.java:490)
	at org.apache.river.jeri.internal.runtime.Target.access$000(Target.java:57)
	at org.apache.river.jeri.internal.runtime.Target$1.run(Target.java:466)
	at org.apache.river.start.AggregatePolicyProvider$AggregateSecurityContext$2.run(AggregatePolicyProvider.java:593)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.river.jeri.internal.runtime.Target.dispatch(Target.java:463)
	at org.apache.river.jeri.internal.runtime.Target.dispatch(Target.java:428)
	at org.apache.river.jeri.internal.runtime.DgcRequestDispatcher.dispatch(DgcRequestDispatcher.java:222)
	at net.jini.jeri.connection.ServerConnectionManager$Dispatcher.dispatch(ServerConnectionManager.java:147)
	at org.apache.river.jeri.internal.mux.MuxServer$1$1.run(MuxServer.java:247)
	at org.apache.river.start.AggregatePolicyProvider$AggregateSecurityContext$1.run(AggregatePolicyProvider.java:579)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.river.jeri.internal.mux.MuxServer$1.run(MuxServer.java:243)
	at org.apache.river.thread.ThreadPool$Task.run(ThreadPool.java:172)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
