### ISSUE TITLE
java.security.Permissions race condition preventing resolution of unresolved permissions affects net.jini.loader.pref.PreferredClassLoader

### ISSUE THREAD

**Issue by pfirmstone** [pfirmstone/JGDMS#5]
Running org/apache/river/test/impl/joinmanager/LeaseRenewDurRFE.td
Time is Sun Sep 04 09:18:27 AEST 2016
Starting test in separate process with command:
'C:\Program Files\Java\jdk1.8.0_60\jre\bin\java' -Djava.security.manager=org.apache.river.api.security.CombinerSecurityManager -Djava.security.policy=file:/C:/Users/PeteFir/Documents/river-internet/qa/harness/policy/defaulttest.policy -cp C:\Users\PeteFir\Documents\river-internet\qa\lib\jiniharness.jar;C:\Users\PeteFir\Documents\river-internet\qa\lib\jinitests.jar;C:\Users\PeteFir\Documents\river-internet\lib\jsk-platform.jar;C:\Users\PeteFir\Documents\river-internet\lib\jsk-lib.jar;C:\Users\PeteFir\Documents\river-internet\lib\high-scale-lib.jar -ea -esa -Djava.security.debug=access:failure -Dorg.apache.river.jsk.port=9080 -Dorg.apache.river.qa.port=9081 -Dorg.apache.river.jsk.home=C:\Users\PeteFir\Documents\river-internet -Dorg.apache.river.qa.home=C:\Users\PeteFir\Documents\river-internet\qa -Dorg.apache.river.qa.harness.harnessJar=C:\Users\PeteFir\Documents\river-internet\qa\lib\jiniharness.jar -Dorg.apache.river.qa.harness.testJar=C:\Users\PeteFir\Documents\river-internet\qa\lib\jinitests.jar -Dorg.apache.river.qa.harness.runjiniserver=true -Dorg.apache.river.qa.harness.runkitserver=true -Djava.security.properties=file:/C:/Users/PeteFir/Documents/river-internet/qa/harness/trust/dynamic-policy.properties -Dorg.apache.river.qa.harness.testhosts= -Djava.util.logging.config.file=C:\Users\PeteFir\Documents\river-internet\qa\src\org\apache\river\test\resources\qa1.logging -Dnet.jini.core.lookup.ServiceRegistrar.portAbitraryIfInUse=true -Dorg.apache.river.test.home=C:\Users\PeteFir\Documents\river-internet\qa -Dorg.apache.river.test.port=9082 -Dorg.apache.river.qa.harness.policies=file:/C:/Users/PeteFir/Documents/river-internet/qa/src/org/apache/river/test/resources/jinitest.policy org.apache.river.qa.harness.MasterTest org/apache/river/test/impl/joinmanager/LeaseRenewDurRFE.td 
access: access denied ("org.apache.river.api.io.DeSerializationPermission" "ATOMIC")
java.lang.Exception: Stack trace
    at java.lang.Thread.dumpStack(Thread.java:1329)
    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:462)
    at org.apache.river.api.security.CombinerSecurityManager.checkPermission(CombinerSecurityManager.java:332)
    at org.apache.river.api.io.ObjectStreamClassContainer.deSerializationPermitted(ObjectStreamClassContainer.java:127)
    at org.apache.river.api.io.AtomicMarshalInputStream.readNewObject(AtomicMarshalInputStream.java:2292)
    at org.apache.river.api.io.AtomicMarshalInputStream.readNonPrimitiveContent(AtomicMarshalInputStream.java:933)
    at org.apache.river.api.io.AtomicMarshalInputStream.readObject(AtomicMarshalInputStream.java:2743)
    at org.apache.river.api.io.AtomicMarshalInputStream.readFieldValues(AtomicMarshalInputStream.java:1148)
    at org.apache.river.api.io.AtomicMarshalInputStream.readFields(AtomicMarshalInputStream.java:1098)
    at org.apache.river.api.io.AtomicMarshalInputStream.instantiateAtomicSerialOrDiscard(AtomicMarshalInputStream.java:2509)
    at org.apache.river.api.io.AtomicMarshalInputStream.readNewObject(AtomicMarshalInputStream.java:2294)
    at org.apache.river.api.io.AtomicMarshalInputStream.readNonPrimitiveContent(AtomicMarshalInputStream.java:933)
    at org.apache.river.api.io.AtomicMarshalInputStream.readObject(AtomicMarshalInputStream.java:2743)
    at org.apache.river.api.io.AtomicMarshalInputStream.readObjectOverride(AtomicMarshalInputStream.java:2644)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:365)
    at org.apache.river.jeri.internal.runtime.Util.unmarshalValue(Util.java:225)
    at net.jini.jeri.BasicInvocationHandler.unmarshalReturn(BasicInvocationHandler.java:1359)
    at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:886)
    at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:708)
    at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:577)
    at org.apache.river.reggie.$Proxy3.register(Unknown Source)
    at org.apache.river.reggie.RegistrarProxy.register(RegistrarProxy.java:146)
    at org.apache.river.test.impl.joinmanager.LeaseRenewDurRFE.construct(LeaseRenewDurRFE.java:298)
    at org.apache.river.qa.harness.MasterTest.doTest(MasterTest.java:220)
    at org.apache.river.qa.harness.MasterTest.main(MasterTest.java:144)
access: domain that failed DomainCombinerSecurityManager full stack: 
ProtectionDomain  (http://AULH12GV32:9080/reggie-dl.jar <no signer certificates>)
 net.jini.loader.pref.PreferredClassLoader@653222["http://AULH12GV32:9080/reggie-dl.jar http://AULH12GV32:9080/jsk-dl.jar"]
 <no principals>
 java.security.Permissions@1d4cc9e (
 ("java.net.NetPermission" "getNetworkInformation")
 ("java.lang.RuntimePermission" "setFactory")
 ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.action")
 ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.ssl")
 ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.util")
 ("java.lang.RuntimePermission" "accessClassInPackage.com.sun.proxy")
 ("java.lang.RuntimePermission" "getClassLoader")
 ("java.lang.RuntimePermission" "accessClassInPackage.jdk.internal.misc")
 ("java.lang.RuntimePermission" "setIO")
 ("java.lang.RuntimePermission" "accessClassInPackage.sun.util.logging.resources")
 ("java.lang.RuntimePermission" "stopThread")
 ("java.io.FilePermission" "-" "read")
 ("java.io.FilePermission" "C:\Users\PeteFir\Documents\river-internet\qa\lib-" "read")
 ("java.io.FilePermission" "C:\Users\PeteFir\Documents\river-internet\lib-" "read")
 (unresolved org.apache.river.phoenix.ExecPermission /bin/javax null)
 (unresolved org.apache.river.phoenix.ExecOptionPermission \* null)
 (unresolved org.apache.river.api.io.DeSerializationPermission ATOMIC null)
 ("java.util.PropertyPermission" "java.specification.version" "read")
 ("java.util.PropertyPermission" "java.version" "read")
 ("java.util.PropertyPermission" "os.arch" "read")
 ("java.util.PropertyPermission" "java.specification.vendor" "read")
 ("java.util.PropertyPermission" "java.vm.specification.name" "read")
 ("java.util.PropertyPermission" "_" "read")
 ("java.util.PropertyPermission" "java.vm.vendor" "read")
 ("java.util.PropertyPermission" "path.separator" "read")
 ("java.util.PropertyPermission" "os.version" "read")
 ("java.util.PropertyPermission" "file.separator" "read")
 ("java.util.PropertyPermission" "line.separator" "read")
 ("java.util.PropertyPermission" "java.vm.specification.vendor" "read")
 ("java.util.PropertyPermission" "java.specification.name" "read")
 ("java.util.PropertyPermission" "java.vendor.url" "read")
 ("java.util.PropertyPermission" "java.vendor" "read")
 ("java.util.PropertyPermission" "java.vm.version" "read")
 ("java.util.PropertyPermission" "java.vm.name" "read")
 ("java.util.PropertyPermission" "java.vm.specification.version" "read")
 ("java.util.PropertyPermission" "os.name" "read")
 ("java.util.PropertyPermission" "java.class.version" "read")
 ("java.util.PropertyPermission" "org.apache.river.test.spec.io.util.FakeIntegrityVerifier.throwException" "write")
 ("java.util.PropertyPermission" "org.apache.river.reggie.enableImplToStubReplacement" "read")
 ("java.lang.reflect.ReflectPermission" "newProxyInPackage.org.apache.river.fiddler")
 ("java.lang.reflect.ReflectPermission" "newProxyInPackage.org.apache.river.reggie")
 ("java.lang.reflect.ReflectPermission" "newProxyInPackage.org.apache.river.outrigger")
 ("java.lang.reflect.ReflectPermission" "newProxyInPackage.org.apache.river.mercury")
 ("java.lang.reflect.ReflectPermission" "newProxyInPackage.org.apache.river.norm")
 ("java.net.URLPermission" "http:_" "GET:")
 ("java.net.SocketPermission" "AULH12GV32" "connect,accept,resolve")
 ("java.net.SocketPermission" "localhost:0" "listen,resolve")
 ("java.net.SocketPermission" "*:1024-" "connect,accept,resolve")
)
Test process was destroyed and returned code 1
org/apache/river/test/impl/joinmanager/LeaseRenewDurRFE.td
Test Failed: Unexpected Exception in construct: java.security.AccessControlException: access denied ("org.apache.river.api.io.DeSerializationPermission" "ATOMIC")

**Comment by pfirmstone** [comment]
Suggest replacing the use of java.security.Permissions in net.jini.loader.pref.PreferredClassLoader with org.apache.river.api.security.ConcurrentPermissions which was designed to address this issue.  

Alternatively a more scalable option is to use DynamicPolicy to dynamically grant permissions instead, as our policy providers thread confines java.security.Permissions.

**Comment by pfirmstone** [comment]
False positive on this occasion, DomainCombinerSecurityManager was in force, since it checks ProtectionDomain's concurrently, it doesn't know which causes the failure and as such, prints out all domains.  The unresolved permissions are actually a debugging artifact, where a new Permissions instance is created, permissions may appear as unresolved.  Thus while the bug exists in java.security.Permissions and I have seen it in action, all domains printed must be first checked for the missing permission before it is safe to assume it unresolved.

As a result this issue is closed.
