### ISSUE TITLE
CombinerSecurityManager unable to create new Threads due to missing permission.

### ISSUE THREAD

**Issue by pfirmstone** [pfirmstone/JGDMS#87]
CombinerSecurityManager has a ThreadFactory that creates threads with a descriptive name so that developers can easily debug thread dumps.  Unfortunately this also means that if CombinerSecurityManager doesn't itself have permission java.lang.RuntimePermission "modifyThreadGroup" it will not be able to create new threads.

ControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at org.apache.river.api.security.CombinerSecurityManager.checkPermission(CombinerSecurityManager.java:362)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at org.apache.river.api.security.CombinerSecurityManager.checkPermission(CombinerSecurityManager.java:257)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at java.lang.SecurityManager.checkAccess(SecurityManager.java:729)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at java.lang.Thread.init(Thread.java:394)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at java.lang.Thread.init(Thread.java:349)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at java.lang.Thread.<init>(Thread.java:551)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at org.apache.river.api.security.CombinerSecurityManager$1.newThread(CombinerSecurityManager.java:196)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:619)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:932)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
ActSys-err: 01/09/2019 8:18:21 PM:Group-0:err:	at org.apache.river.api.security.CombinerSecurityManager$DelegateProtectionDomain.implies(CombinerSecurityManager.java:528)

**Comment by pfirmstone** [comment]
The fix was accidentally included in the merge commit.

https://github.com/pfirmstone/JGDMS/commit/179d364d9c83c2c34bd26ea0804ab8c901e8d140
